// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA70JCJkfZNhO34o6zuBgtZz7LLAXvakqs',
    appId: '1:1003493508218:web:e7abbf5dafe6d197c0a7c3',
    messagingSenderId: '1003493508218',
    projectId: 'todoapp-fec9d',
    authDomain: 'todoapp-fec9d.firebaseapp.com',
    storageBucket: 'todoapp-fec9d.appspot.com',
    measurementId: 'G-0X73J0LXKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2d2G7d2w_FMYvfAkyPHxzS9uMMIEVFQ4',
    appId: '1:1003493508218:android:a835d93d5649fce1c0a7c3',
    messagingSenderId: '1003493508218',
    projectId: 'todoapp-fec9d',
    storageBucket: 'todoapp-fec9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmpO2-XVvrRyS03LP1MKRjst_ngbVewOA',
    appId: '1:1003493508218:ios:fabda8e48a32de11c0a7c3',
    messagingSenderId: '1003493508218',
    projectId: 'todoapp-fec9d',
    storageBucket: 'todoapp-fec9d.appspot.com',
    iosBundleId: 'com.harikrashna.todoAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmpO2-XVvrRyS03LP1MKRjst_ngbVewOA',
    appId: '1:1003493508218:ios:285f9734e6a2776cc0a7c3',
    messagingSenderId: '1003493508218',
    projectId: 'todoapp-fec9d',
    storageBucket: 'todoapp-fec9d.appspot.com',
    iosBundleId: 'com.harikrashna.todoAppWithFirebase.RunnerTests',
  );
}
